name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-package:
    runs-on: ubuntu-22.04
    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 构建镜像并导出为 tar 文件
      - name: Build and export to Docker image tar
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: my-stream:0801
          push: false
          outputs: type=docker,dest=image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. 上传 tar 文件保留3天
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 3 # 下载保留3天
